name: CI
on:
  pull_request:
    types: [opened, synchronize, reopened] # these are the defaults - synchronize means 'commits pushed to PR'

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  golang-ci:
    uses: cccteam/github-workflows/.github/workflows/golang-ci.yml@4987befcc33b8c6a81741990bb9818d55e7446fe # v6.0.0
    with:
      build-tags: '[""]'
      golangci-lint-version: 'v2.11.4'
  semantic-pull-request-title:
    uses: cccteam/github-workflows/.github/workflows/semantic-pull-request-title.yml@4987befcc33b8c6a81741990bb9818d55e7446fe # 6.0.0
